### ISSUE TITLE
About released files on NPM

### ISSUE THREAD

**Issue by pvnr0082t** [XadillaX/fbibik-json#7]
Hi @XadillaX ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team and we want to host the library.
I found that there is no `fjson.js` in `v0.0.1- v0.0.5` but `index.js`. I'd like to confirm if the `index.js` renamed to `fjson.js` after `v0.0.6`?
Thank you.

https://github.com/cdnjs/cdnjs/issues/8452
https://github.com/cdnjs/cdnjs/pull/9053

**Comment by XadillaX** [comment]
Yes I changed the filename since 0.0.6.
